version: '3'
services:
  python3:
    restart: always
    build: .
    command: python3 ine_disease_diagnosis/server.py
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt